# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sotagrpc.v1 import camera_pb2 as sotagrpc_dot_v1_dot_camera__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sotagrpc/v1/camera_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CameraServiceStub(object):
    """--------------------
    サービス定義
    --------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConfigureDetection = channel.unary_unary(
                '/sotagrpc.v1.CameraService/ConfigureDetection',
                request_serializer=sotagrpc_dot_v1_dot_camera__pb2.ConfigureDetectionRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_camera__pb2.ConfigureDetectionResponse.FromString,
                _registered_method=True)
        self.StartFaceTracking = channel.unary_unary(
                '/sotagrpc.v1.CameraService/StartFaceTracking',
                request_serializer=sotagrpc_dot_v1_dot_camera__pb2.StartFaceTrackingRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_camera__pb2.StartFaceTrackingResponse.FromString,
                _registered_method=True)
        self.StopFaceTracking = channel.unary_unary(
                '/sotagrpc.v1.CameraService/StopFaceTracking',
                request_serializer=sotagrpc_dot_v1_dot_camera__pb2.StopFaceTrackingRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_camera__pb2.StopFaceTrackingResponse.FromString,
                _registered_method=True)
        self.SubscribeFaceDetections = channel.unary_stream(
                '/sotagrpc.v1.CameraService/SubscribeFaceDetections',
                request_serializer=sotagrpc_dot_v1_dot_camera__pb2.SubscribeFaceDetectionsRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_camera__pb2.FaceDetectionsFrame.FromString,
                _registered_method=True)
        self.TakePicture = channel.unary_unary(
                '/sotagrpc.v1.CameraService/TakePicture',
                request_serializer=sotagrpc_dot_v1_dot_camera__pb2.TakePictureRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_camera__pb2.TakePictureResponse.FromString,
                _registered_method=True)
        self.RegisterUser = channel.unary_unary(
                '/sotagrpc.v1.CameraService/RegisterUser',
                request_serializer=sotagrpc_dot_v1_dot_camera__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_camera__pb2.RegisterUserResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/sotagrpc.v1.CameraService/ListUsers',
                request_serializer=sotagrpc_dot_v1_dot_camera__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_camera__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/sotagrpc.v1.CameraService/DeleteUser',
                request_serializer=sotagrpc_dot_v1_dot_camera__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_camera__pb2.DeleteUserResponse.FromString,
                _registered_method=True)


class CameraServiceServicer(object):
    """--------------------
    サービス定義
    --------------------

    """

    def ConfigureDetection(self, request, context):
        """顔認識関連の各種機能を有効化/無効化する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartFaceTracking(self, request, context):
        """顔追跡を開始する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopFaceTracking(self, request, context):
        """顔追跡を停止する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeFaceDetections(self, request, context):
        """顔認識結果のストリーミング配信を購読する (サーバープッシュ)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakePicture(self, request, context):
        """写真を撮影する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterUser(self, request, context):
        """顔をユーザーとして登録する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """登録されているユーザーのリストを取得する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """ユーザーを削除する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConfigureDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureDetection,
                    request_deserializer=sotagrpc_dot_v1_dot_camera__pb2.ConfigureDetectionRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_camera__pb2.ConfigureDetectionResponse.SerializeToString,
            ),
            'StartFaceTracking': grpc.unary_unary_rpc_method_handler(
                    servicer.StartFaceTracking,
                    request_deserializer=sotagrpc_dot_v1_dot_camera__pb2.StartFaceTrackingRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_camera__pb2.StartFaceTrackingResponse.SerializeToString,
            ),
            'StopFaceTracking': grpc.unary_unary_rpc_method_handler(
                    servicer.StopFaceTracking,
                    request_deserializer=sotagrpc_dot_v1_dot_camera__pb2.StopFaceTrackingRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_camera__pb2.StopFaceTrackingResponse.SerializeToString,
            ),
            'SubscribeFaceDetections': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeFaceDetections,
                    request_deserializer=sotagrpc_dot_v1_dot_camera__pb2.SubscribeFaceDetectionsRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_camera__pb2.FaceDetectionsFrame.SerializeToString,
            ),
            'TakePicture': grpc.unary_unary_rpc_method_handler(
                    servicer.TakePicture,
                    request_deserializer=sotagrpc_dot_v1_dot_camera__pb2.TakePictureRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_camera__pb2.TakePictureResponse.SerializeToString,
            ),
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=sotagrpc_dot_v1_dot_camera__pb2.RegisterUserRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_camera__pb2.RegisterUserResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=sotagrpc_dot_v1_dot_camera__pb2.ListUsersRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_camera__pb2.ListUsersResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=sotagrpc_dot_v1_dot_camera__pb2.DeleteUserRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_camera__pb2.DeleteUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sotagrpc.v1.CameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sotagrpc.v1.CameraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CameraService(object):
    """--------------------
    サービス定義
    --------------------

    """

    @staticmethod
    def ConfigureDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.CameraService/ConfigureDetection',
            sotagrpc_dot_v1_dot_camera__pb2.ConfigureDetectionRequest.SerializeToString,
            sotagrpc_dot_v1_dot_camera__pb2.ConfigureDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartFaceTracking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.CameraService/StartFaceTracking',
            sotagrpc_dot_v1_dot_camera__pb2.StartFaceTrackingRequest.SerializeToString,
            sotagrpc_dot_v1_dot_camera__pb2.StartFaceTrackingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopFaceTracking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.CameraService/StopFaceTracking',
            sotagrpc_dot_v1_dot_camera__pb2.StopFaceTrackingRequest.SerializeToString,
            sotagrpc_dot_v1_dot_camera__pb2.StopFaceTrackingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeFaceDetections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sotagrpc.v1.CameraService/SubscribeFaceDetections',
            sotagrpc_dot_v1_dot_camera__pb2.SubscribeFaceDetectionsRequest.SerializeToString,
            sotagrpc_dot_v1_dot_camera__pb2.FaceDetectionsFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakePicture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.CameraService/TakePicture',
            sotagrpc_dot_v1_dot_camera__pb2.TakePictureRequest.SerializeToString,
            sotagrpc_dot_v1_dot_camera__pb2.TakePictureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.CameraService/RegisterUser',
            sotagrpc_dot_v1_dot_camera__pb2.RegisterUserRequest.SerializeToString,
            sotagrpc_dot_v1_dot_camera__pb2.RegisterUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.CameraService/ListUsers',
            sotagrpc_dot_v1_dot_camera__pb2.ListUsersRequest.SerializeToString,
            sotagrpc_dot_v1_dot_camera__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.CameraService/DeleteUser',
            sotagrpc_dot_v1_dot_camera__pb2.DeleteUserRequest.SerializeToString,
            sotagrpc_dot_v1_dot_camera__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
