# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sotagrpc.v1 import robotlib_pb2 as sotagrpc_dot_v1_dot_robotlib__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sotagrpc/v1/robotlib_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConfigurationServiceStub(object):
    """--------------------
    サービス定義
    --------------------

    FirmwareやIPアドレスなど，Sota自身の情報を取得する機能を提供
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIPAddress = channel.unary_unary(
                '/sotagrpc.v1.ConfigurationService/GetIPAddress',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetIPAddressRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetIPAddressResponse.FromString,
                _registered_method=True)
        self.GetFirmwareVersion = channel.unary_unary(
                '/sotagrpc.v1.ConfigurationService/GetFirmwareVersion',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetFirmwareVersionRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetFirmwareVersionResponse.FromString,
                _registered_method=True)


class ConfigurationServiceServicer(object):
    """--------------------
    サービス定義
    --------------------

    FirmwareやIPアドレスなど，Sota自身の情報を取得する機能を提供
    """

    def GetIPAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFirmwareVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigurationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIPAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIPAddress,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetIPAddressRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetIPAddressResponse.SerializeToString,
            ),
            'GetFirmwareVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFirmwareVersion,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetFirmwareVersionRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetFirmwareVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sotagrpc.v1.ConfigurationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sotagrpc.v1.ConfigurationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigurationService(object):
    """--------------------
    サービス定義
    --------------------

    FirmwareやIPアドレスなど，Sota自身の情報を取得する機能を提供
    """

    @staticmethod
    def GetIPAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.ConfigurationService/GetIPAddress',
            sotagrpc_dot_v1_dot_robotlib__pb2.GetIPAddressRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.GetIPAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFirmwareVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.ConfigurationService/GetFirmwareVersion',
            sotagrpc_dot_v1_dot_robotlib__pb2.GetFirmwareVersionRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.GetFirmwareVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MotionServiceStub(object):
    """CRobotMotion / CSotaMotion の機能を提供
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServoOn = channel.unary_unary(
                '/sotagrpc.v1.MotionService/ServoOn',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.ServoOnRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.ServoOnResponse.FromString,
                _registered_method=True)
        self.ServoOff = channel.unary_unary(
                '/sotagrpc.v1.MotionService/ServoOff',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.ServoOffRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.ServoOffResponse.FromString,
                _registered_method=True)
        self.PlayPose = channel.unary_unary(
                '/sotagrpc.v1.MotionService/PlayPose',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayPoseRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayPoseResponse.FromString,
                _registered_method=True)
        self.GetCurrentPose = channel.unary_unary(
                '/sotagrpc.v1.MotionService/GetCurrentPose',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetCurrentPoseRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.Pose.FromString,
                _registered_method=True)
        self.IsEndInterAll = channel.unary_unary(
                '/sotagrpc.v1.MotionService/IsEndInterAll',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsEndInterAllRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsEndInterAllResponse.FromString,
                _registered_method=True)
        self.GetPowerStatus = channel.unary_unary(
                '/sotagrpc.v1.MotionService/GetPowerStatus',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetPowerStatusRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetPowerStatusResponse.FromString,
                _registered_method=True)
        self.GetButtonState = channel.unary_unary(
                '/sotagrpc.v1.MotionService/GetButtonState',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetButtonStateRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetButtonStateResponse.FromString,
                _registered_method=True)
        self.SetCollisionDetection = channel.unary_unary(
                '/sotagrpc.v1.MotionService/SetCollisionDetection',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetCollisionDetectionRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetCollisionDetectionResponse.FromString,
                _registered_method=True)
        self.SetMouthLedVoiceSync = channel.unary_unary(
                '/sotagrpc.v1.MotionService/SetMouthLedVoiceSync',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetMouthLedVoiceSyncRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetMouthLedVoiceSyncResponse.FromString,
                _registered_method=True)


class MotionServiceServicer(object):
    """CRobotMotion / CSotaMotion の機能を提供
    """

    def ServoOn(self, request, context):
        """(変更なし)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServoOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsEndInterAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPowerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetButtonState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCollisionDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMouthLedVoiceSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServoOn': grpc.unary_unary_rpc_method_handler(
                    servicer.ServoOn,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.ServoOnRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.ServoOnResponse.SerializeToString,
            ),
            'ServoOff': grpc.unary_unary_rpc_method_handler(
                    servicer.ServoOff,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.ServoOffRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.ServoOffResponse.SerializeToString,
            ),
            'PlayPose': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayPose,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayPoseRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayPoseResponse.SerializeToString,
            ),
            'GetCurrentPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentPose,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetCurrentPoseRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.Pose.SerializeToString,
            ),
            'IsEndInterAll': grpc.unary_unary_rpc_method_handler(
                    servicer.IsEndInterAll,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsEndInterAllRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsEndInterAllResponse.SerializeToString,
            ),
            'GetPowerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPowerStatus,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetPowerStatusRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetPowerStatusResponse.SerializeToString,
            ),
            'GetButtonState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetButtonState,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetButtonStateRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetButtonStateResponse.SerializeToString,
            ),
            'SetCollisionDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCollisionDetection,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetCollisionDetectionRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetCollisionDetectionResponse.SerializeToString,
            ),
            'SetMouthLedVoiceSync': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMouthLedVoiceSync,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetMouthLedVoiceSyncRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetMouthLedVoiceSyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sotagrpc.v1.MotionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sotagrpc.v1.MotionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MotionService(object):
    """CRobotMotion / CSotaMotion の機能を提供
    """

    @staticmethod
    def ServoOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionService/ServoOn',
            sotagrpc_dot_v1_dot_robotlib__pb2.ServoOnRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.ServoOnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServoOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionService/ServoOff',
            sotagrpc_dot_v1_dot_robotlib__pb2.ServoOffRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.ServoOffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionService/PlayPose',
            sotagrpc_dot_v1_dot_robotlib__pb2.PlayPoseRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.PlayPoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionService/GetCurrentPose',
            sotagrpc_dot_v1_dot_robotlib__pb2.GetCurrentPoseRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.Pose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsEndInterAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionService/IsEndInterAll',
            sotagrpc_dot_v1_dot_robotlib__pb2.IsEndInterAllRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.IsEndInterAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPowerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionService/GetPowerStatus',
            sotagrpc_dot_v1_dot_robotlib__pb2.GetPowerStatusRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.GetPowerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetButtonState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionService/GetButtonState',
            sotagrpc_dot_v1_dot_robotlib__pb2.GetButtonStateRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.GetButtonStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCollisionDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionService/SetCollisionDetection',
            sotagrpc_dot_v1_dot_robotlib__pb2.SetCollisionDetectionRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.SetCollisionDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMouthLedVoiceSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionService/SetMouthLedVoiceSync',
            sotagrpc_dot_v1_dot_robotlib__pb2.SetMouthLedVoiceSyncRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.SetMouthLedVoiceSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PlaybackServiceStub(object):
    """CPlayWave の機能を提供
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayAudio = channel.unary_unary(
                '/sotagrpc.v1.PlaybackService/PlayAudio',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayAudioRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayAudioResponse.FromString,
                _registered_method=True)
        self.PlayLocalAudio = channel.unary_unary(
                '/sotagrpc.v1.PlaybackService/PlayLocalAudio',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayLocalAudioRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayAudioResponse.FromString,
                _registered_method=True)
        self.StopAudio = channel.unary_unary(
                '/sotagrpc.v1.PlaybackService/StopAudio',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.StopAudioRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.StopAudioResponse.FromString,
                _registered_method=True)
        self.IsAudioPlaying = channel.unary_unary(
                '/sotagrpc.v1.PlaybackService/IsAudioPlaying',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsAudioPlayingRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsAudioPlayingResponse.FromString,
                _registered_method=True)


class PlaybackServiceServicer(object):
    """CPlayWave の機能を提供
    """

    def PlayAudio(self, request, context):
        """音声データ(wav)を再生し、再生IDを返す
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayLocalAudio(self, request, context):
        """Sotaローカルに保存された音声データ(wav)を再生し、再生IDを返す
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAudio(self, request, context):
        """rpc SaveAudioToLocal(SaveAudioToLocalRequest) returns RequestStatus;

        指定したIDの音声再生を停止する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsAudioPlaying(self, request, context):
        """指定したIDの音声が再生中か確認する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaybackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayAudio,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayAudioRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayAudioResponse.SerializeToString,
            ),
            'PlayLocalAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayLocalAudio,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayLocalAudioRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.PlayAudioResponse.SerializeToString,
            ),
            'StopAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAudio,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.StopAudioRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.StopAudioResponse.SerializeToString,
            ),
            'IsAudioPlaying': grpc.unary_unary_rpc_method_handler(
                    servicer.IsAudioPlaying,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsAudioPlayingRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsAudioPlayingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sotagrpc.v1.PlaybackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sotagrpc.v1.PlaybackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaybackService(object):
    """CPlayWave の機能を提供
    """

    @staticmethod
    def PlayAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.PlaybackService/PlayAudio',
            sotagrpc_dot_v1_dot_robotlib__pb2.PlayAudioRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.PlayAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayLocalAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.PlaybackService/PlayLocalAudio',
            sotagrpc_dot_v1_dot_robotlib__pb2.PlayLocalAudioRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.PlayAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.PlaybackService/StopAudio',
            sotagrpc_dot_v1_dot_robotlib__pb2.StopAudioRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.StopAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsAudioPlaying(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.PlaybackService/IsAudioPlaying',
            sotagrpc_dot_v1_dot_robotlib__pb2.IsAudioPlayingRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.IsAudioPlayingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RecordingServiceStub(object):
    """(RecordingServiceとIntelligentMicServiceは変更なし)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRecording = channel.unary_unary(
                '/sotagrpc.v1.RecordingService/StartRecording',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.StartRecordingRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.StartRecordingResponse.FromString,
                _registered_method=True)
        self.StopRecording = channel.unary_unary(
                '/sotagrpc.v1.RecordingService/StopRecording',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.StopRecordingRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.StopRecordingResponse.FromString,
                _registered_method=True)
        self.IsRecording = channel.unary_unary(
                '/sotagrpc.v1.RecordingService/IsRecording',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsRecordingRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsRecordingResponse.FromString,
                _registered_method=True)


class RecordingServiceServicer(object):
    """(RecordingServiceとIntelligentMicServiceは変更なし)
    """

    def StartRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecordingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRecording,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.StartRecordingRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.StartRecordingResponse.SerializeToString,
            ),
            'StopRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRecording,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.StopRecordingRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.StopRecordingResponse.SerializeToString,
            ),
            'IsRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.IsRecording,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsRecordingRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.IsRecordingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sotagrpc.v1.RecordingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sotagrpc.v1.RecordingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecordingService(object):
    """(RecordingServiceとIntelligentMicServiceは変更なし)
    """

    @staticmethod
    def StartRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.RecordingService/StartRecording',
            sotagrpc_dot_v1_dot_robotlib__pb2.StartRecordingRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.StartRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.RecordingService/StopRecording',
            sotagrpc_dot_v1_dot_robotlib__pb2.StopRecordingRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.StopRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.RecordingService/IsRecording',
            sotagrpc_dot_v1_dot_robotlib__pb2.IsRecordingRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.IsRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class IntelligentMicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMode = channel.unary_unary(
                '/sotagrpc.v1.IntelligentMicService/SetMode',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetMicModeRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetMicModeResponse.FromString,
                _registered_method=True)
        self.GetSoundSource = channel.unary_unary(
                '/sotagrpc.v1.IntelligentMicService/GetSoundSource',
                request_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetSoundSourceRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetSoundSourceResponse.FromString,
                _registered_method=True)


class IntelligentMicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSoundSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelligentMicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetMicModeRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.SetMicModeResponse.SerializeToString,
            ),
            'GetSoundSource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSoundSource,
                    request_deserializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetSoundSourceRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_robotlib__pb2.GetSoundSourceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sotagrpc.v1.IntelligentMicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sotagrpc.v1.IntelligentMicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntelligentMicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.IntelligentMicService/SetMode',
            sotagrpc_dot_v1_dot_robotlib__pb2.SetMicModeRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.SetMicModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSoundSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.IntelligentMicService/GetSoundSource',
            sotagrpc_dot_v1_dot_robotlib__pb2.GetSoundSourceRequest.SerializeToString,
            sotagrpc_dot_v1_dot_robotlib__pb2.GetSoundSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
