# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sotagrpc.v1 import common_pb2 as sotagrpc_dot_v1_dot_common__pb2
from sotagrpc.v1 import sotatalk_pb2 as sotagrpc_dot_v1_dot_sotatalk__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sotagrpc/v1/sotatalk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextToSpeechServiceStub(object):
    """--------------------
    サービス定義
    --------------------

    TextToSpeechSota の機能を提供
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTTSData = channel.unary_unary(
                '/sotagrpc.v1.TextToSpeechService/GetTTSData',
                request_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.TTSDataRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.GetTTSDataResponse.FromString,
                _registered_method=True)
        self.say = channel.unary_unary(
                '/sotagrpc.v1.TextToSpeechService/say',
                request_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.TTSDataRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_common__pb2.SuccessResponse.FromString,
                _registered_method=True)


class TextToSpeechServiceServicer(object):
    """--------------------
    サービス定義
    --------------------

    TextToSpeechSota の機能を提供
    """

    def GetTTSData(self, request, context):
        """テキストを音声データに変換する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def say(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextToSpeechServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTTSData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTTSData,
                    request_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.TTSDataRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.GetTTSDataResponse.SerializeToString,
            ),
            'say': grpc.unary_unary_rpc_method_handler(
                    servicer.say,
                    request_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.TTSDataRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_common__pb2.SuccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sotagrpc.v1.TextToSpeechService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sotagrpc.v1.TextToSpeechService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextToSpeechService(object):
    """--------------------
    サービス定義
    --------------------

    TextToSpeechSota の機能を提供
    """

    @staticmethod
    def GetTTSData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.TextToSpeechService/GetTTSData',
            sotagrpc_dot_v1_dot_sotatalk__pb2.TTSDataRequest.SerializeToString,
            sotagrpc_dot_v1_dot_sotatalk__pb2.GetTTSDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def say(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.TextToSpeechService/say',
            sotagrpc_dot_v1_dot_sotatalk__pb2.TTSDataRequest.SerializeToString,
            sotagrpc_dot_v1_dot_common__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SpeechRecognitionServiceStub(object):
    """SpeechRecog の機能を提供
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.unary_unary(
                '/sotagrpc.v1.SpeechRecognitionService/Recognize',
                request_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognitionResult.FromString,
                _registered_method=True)
        self.RecognizeYesOrNo = channel.unary_unary(
                '/sotagrpc.v1.SpeechRecognitionService/RecognizeYesOrNo',
                request_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeYesOrNoRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeYesOrNoResponse.FromString,
                _registered_method=True)
        self.RecognizeName = channel.unary_unary(
                '/sotagrpc.v1.SpeechRecognitionService/RecognizeName',
                request_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNameRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNameResponse.FromString,
                _registered_method=True)
        self.RecognizeNames = channel.unary_unary(
                '/sotagrpc.v1.SpeechRecognitionService/RecognizeNames',
                request_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNamesRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNamesResponse.FromString,
                _registered_method=True)
        self.RecognizeGeneralResponse = channel.unary_unary(
                '/sotagrpc.v1.SpeechRecognitionService/RecognizeGeneralResponse',
                request_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeGeneralResponseRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeGeneralResponseResponse.FromString,
                _registered_method=True)


class SpeechRecognitionServiceServicer(object):
    """SpeechRecog の機能を提供
    """

    def Recognize(self, request, context):
        """自由な内容で音声認識を実行する (getRecognition)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeYesOrNo(self, request, context):
        """「はい」または「いいえ」を認識する (getYesorNo)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeName(self, request, context):
        """人の名前を認識する (getName)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeNames(self, request, context):
        """NEW! 複数の名前候補を認識する (getNames)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeGeneralResponse(self, request, context):
        """NEW! 一般的な応答を認識する (getResponse)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechRecognitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognitionResult.SerializeToString,
            ),
            'RecognizeYesOrNo': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeYesOrNo,
                    request_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeYesOrNoRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeYesOrNoResponse.SerializeToString,
            ),
            'RecognizeName': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeName,
                    request_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNameRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNameResponse.SerializeToString,
            ),
            'RecognizeNames': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeNames,
                    request_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNamesRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNamesResponse.SerializeToString,
            ),
            'RecognizeGeneralResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeGeneralResponse,
                    request_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeGeneralResponseRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeGeneralResponseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sotagrpc.v1.SpeechRecognitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sotagrpc.v1.SpeechRecognitionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeechRecognitionService(object):
    """SpeechRecog の機能を提供
    """

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.SpeechRecognitionService/Recognize',
            sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeRequest.SerializeToString,
            sotagrpc_dot_v1_dot_sotatalk__pb2.RecognitionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeYesOrNo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.SpeechRecognitionService/RecognizeYesOrNo',
            sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeYesOrNoRequest.SerializeToString,
            sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeYesOrNoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.SpeechRecognitionService/RecognizeName',
            sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNameRequest.SerializeToString,
            sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.SpeechRecognitionService/RecognizeNames',
            sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNamesRequest.SerializeToString,
            sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeNamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeGeneralResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.SpeechRecognitionService/RecognizeGeneralResponse',
            sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeGeneralResponseRequest.SerializeToString,
            sotagrpc_dot_v1_dot_sotatalk__pb2.RecognizeGeneralResponseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MotionAsSotaWishServiceStub(object):
    """MotionAsSotaWish の機能を提供
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayWithMotion = channel.unary_unary(
                '/sotagrpc.v1.MotionAsSotaWishService/SayWithMotion',
                request_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.SayWithMotionRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.SayWithMotionResponse.FromString,
                _registered_method=True)
        self.PlayScene = channel.unary_unary(
                '/sotagrpc.v1.MotionAsSotaWishService/PlayScene',
                request_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.PlaySceneRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.PlaySceneResponse.FromString,
                _registered_method=True)
        self.StartIdling = channel.unary_unary(
                '/sotagrpc.v1.MotionAsSotaWishService/StartIdling',
                request_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.StartIdlingRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.StartIdlingResponse.FromString,
                _registered_method=True)
        self.StopIdling = channel.unary_unary(
                '/sotagrpc.v1.MotionAsSotaWishService/StopIdling',
                request_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.StopIdlingRequest.SerializeToString,
                response_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.StopIdlingResponse.FromString,
                _registered_method=True)


class MotionAsSotaWishServiceServicer(object):
    """MotionAsSotaWish の機能を提供
    """

    def SayWithMotion(self, request, context):
        """自然な身振りをしながら発話する (Say)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayScene(self, request, context):
        """事前に定義されたシーンのモーションを再生する (play)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartIdling(self, request, context):
        """アイドリング（待機）モーションを開始・停止する
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopIdling(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotionAsSotaWishServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayWithMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.SayWithMotion,
                    request_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.SayWithMotionRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.SayWithMotionResponse.SerializeToString,
            ),
            'PlayScene': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayScene,
                    request_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.PlaySceneRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.PlaySceneResponse.SerializeToString,
            ),
            'StartIdling': grpc.unary_unary_rpc_method_handler(
                    servicer.StartIdling,
                    request_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.StartIdlingRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.StartIdlingResponse.SerializeToString,
            ),
            'StopIdling': grpc.unary_unary_rpc_method_handler(
                    servicer.StopIdling,
                    request_deserializer=sotagrpc_dot_v1_dot_sotatalk__pb2.StopIdlingRequest.FromString,
                    response_serializer=sotagrpc_dot_v1_dot_sotatalk__pb2.StopIdlingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sotagrpc.v1.MotionAsSotaWishService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sotagrpc.v1.MotionAsSotaWishService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MotionAsSotaWishService(object):
    """MotionAsSotaWish の機能を提供
    """

    @staticmethod
    def SayWithMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionAsSotaWishService/SayWithMotion',
            sotagrpc_dot_v1_dot_sotatalk__pb2.SayWithMotionRequest.SerializeToString,
            sotagrpc_dot_v1_dot_sotatalk__pb2.SayWithMotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionAsSotaWishService/PlayScene',
            sotagrpc_dot_v1_dot_sotatalk__pb2.PlaySceneRequest.SerializeToString,
            sotagrpc_dot_v1_dot_sotatalk__pb2.PlaySceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartIdling(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionAsSotaWishService/StartIdling',
            sotagrpc_dot_v1_dot_sotatalk__pb2.StartIdlingRequest.SerializeToString,
            sotagrpc_dot_v1_dot_sotatalk__pb2.StartIdlingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopIdling(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sotagrpc.v1.MotionAsSotaWishService/StopIdling',
            sotagrpc_dot_v1_dot_sotatalk__pb2.StopIdlingRequest.SerializeToString,
            sotagrpc_dot_v1_dot_sotatalk__pb2.StopIdlingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
